# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0002_auto_20160830_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysqlserver',
            old_name='ip',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='oracletarget',
            old_name='ip',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='redisserver',
            old_name='ip',
            new_name='host',
        ),
    ]
