# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0003_auto_20160830_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='log_file',
            field=models.CharField(default=b'/var/log/oet/mirror.log', max_length=100),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='processes',
            field=models.IntegerField(default=4, help_text=b'Max number of processes.'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='reborn',
            field=models.DurationField(default=datetime.timedelta(0, 7200), help_text=b"When can't connect with server, how many seconds to wait to retry. Eg: 0:01:10 for 70 seconds."),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='sock_link',
            field=models.IntegerField(default=1, help_text=b"how many connection at the same time.Don't change this."),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='sock_port',
            field=models.IntegerField(default=15521, help_text=b'Which port to bind the socket server in Mirror.'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='log_level',
            field=models.CharField(choices=[(b'0', b'NOTSET'), (b'10', b'DEBUG'), (b'20', b'INFO'), (b'30', b'WARNING'), (b'40', b'ERROR'), (b'50', b'CRITICAL')], default=b'WARNING', max_length=10),
        ),
    ]
