# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0004_auto_20160912_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfig',
            name='sock_link',
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='sock_addr',
            field=models.GenericIPAddressField(default=b'127.0.0.1', help_text=b'listening Address.'),
        ),
    ]
