# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0005_auto_20160913_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='log_file',
            field=models.CharField(default=b'/product/oet/data/mirror.log', max_length=100),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='log_level',
            field=models.IntegerField(choices=[(0, b'NOTSET'), (10, b'DEBUG'), (20, b'INFO'), (30, b'WARNING'), (40, b'ERROR'), (50, b'CRITICAL')], default=30),
        ),
    ]
