# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0006_auto_20160922_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='log_file',
            field=models.FilePathField(default=b'/product/oet/data/mirror.log'),
        ),
    ]
