# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0011_auto_20160922_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='log_count',
            field=models.IntegerField(default=3, help_text=b'Backup logs count.'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='log_size',
            field=models.IntegerField(default=10, help_text=b"Logfile's size, Unit is MB. Max is 32767."),
        ),
    ]
