# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0013_auto_20160922_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='log_format',
            field=models.CharField(default=b'%(asctime)s - %(name)s - %(levelname)s - %(message)s', max_length=100),
        ),
    ]
