# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0016_auto_20161025_0058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ora11gR2',
            new_name='OraTest',
        ),
        migrations.AlterModelOptions(
            name='oratest',
            options={'verbose_name': "[Table Collections] Oracle Test's table", 'verbose_name_plural': '[Table Collections] Oracle Test'},
        ),
        migrations.AlterField(
            model_name='oracletarget',
            name='table_collection',
            field=models.CharField(choices=[(b'OraTest', b'[Table Collections] Oracle Test'), (b'Ora10g', b'[Table Collections] Oracle 10G'), (b'Ora11g', b'[Table Collections] Oracle 11G'), (b'Ora12c', b'[Table Collections] Oracle 12C')], max_length=30),
        ),
    ]
